CREATE SCHEMA hadid;
GO
CREATE TABLE hadid.Roles (Id uniqueidentifier NOT NULL PRIMARY KEY, Name nvarchar(80) NOT NULL UNIQUE, Description nvarchar(300) NULL, CreatedAt datetimeoffset NOT NULL, UpdatedAt datetimeoffset NOT NULL, IsDeleted bit NOT NULL DEFAULT 0, DeletedAt datetimeoffset NULL);
CREATE TABLE hadid.Permissions (Id uniqueidentifier NOT NULL PRIMARY KEY, [Key] nvarchar(160) NOT NULL UNIQUE, Name nvarchar(160) NOT NULL, Module nvarchar(80) NULL, CreatedAt datetimeoffset NOT NULL, UpdatedAt datetimeoffset NOT NULL, IsDeleted bit NOT NULL DEFAULT 0, DeletedAt datetimeoffset NULL);
CREATE TABLE hadid.Users (Id uniqueidentifier NOT NULL PRIMARY KEY, FullName nvarchar(200) NOT NULL, Email nvarchar(256) NOT NULL UNIQUE, PasswordHash nvarchar(500) NOT NULL, Phone nvarchar(50) NULL, Status int NOT NULL, RoleId uniqueidentifier NOT NULL FOREIGN KEY REFERENCES hadid.Roles(Id), CreatedAt datetimeoffset NOT NULL, UpdatedAt datetimeoffset NOT NULL, IsDeleted bit NOT NULL DEFAULT 0, DeletedAt datetimeoffset NULL);
CREATE TABLE hadid.Customers (Id uniqueidentifier NOT NULL PRIMARY KEY, Name nvarchar(250) NOT NULL, Type int NOT NULL, Phone nvarchar(50) NOT NULL, Email nvarchar(256) NULL, Address nvarchar(500) NULL, ContactPerson nvarchar(200) NULL, CompanyName nvarchar(250) NULL, TaxNumber nvarchar(80) NULL, Status int NOT NULL, CreatedAt datetimeoffset NOT NULL, UpdatedAt datetimeoffset NOT NULL, IsDeleted bit NOT NULL DEFAULT 0, DeletedAt datetimeoffset NULL);
CREATE TABLE hadid.Companies (Id uniqueidentifier NOT NULL PRIMARY KEY, Name nvarchar(250) NOT NULL, TaxNumber nvarchar(80) NULL, ContactPerson nvarchar(200) NULL, Phone nvarchar(50) NOT NULL, Email nvarchar(256) NULL, Address nvarchar(500) NULL, CreatedAt datetimeoffset NOT NULL, UpdatedAt datetimeoffset NOT NULL, IsDeleted bit NOT NULL DEFAULT 0, DeletedAt datetimeoffset NULL);
CREATE TABLE hadid.Schools (Id uniqueidentifier NOT NULL PRIMARY KEY, Name nvarchar(250) NOT NULL, PrincipalName nvarchar(200) NULL, Phone nvarchar(50) NOT NULL, Email nvarchar(256) NULL, Address nvarchar(500) NULL, StudentCapacity int NOT NULL, CreatedAt datetimeoffset NOT NULL, UpdatedAt datetimeoffset NOT NULL, IsDeleted bit NOT NULL DEFAULT 0, DeletedAt datetimeoffset NULL);
CREATE TABLE hadid.Vehicles (Id uniqueidentifier NOT NULL PRIMARY KEY, Name nvarchar(200) NOT NULL, Type int NOT NULL, PlateNumber nvarchar(40) NOT NULL UNIQUE, Capacity int NOT NULL, Model nvarchar(120) NULL, [Year] int NULL, HasAc bit NOT NULL, HasWifi bit NOT NULL, HasLuggageSpace bit NOT NULL, ComfortLevel int NOT NULL, Status int NOT NULL, ImageUrl nvarchar(1000) NULL, Notes nvarchar(max) NULL, LastMaintenanceDate date NULL, NextMaintenanceDate date NULL, CreatedAt datetimeoffset NOT NULL, UpdatedAt datetimeoffset NOT NULL, IsDeleted bit NOT NULL DEFAULT 0, DeletedAt datetimeoffset NULL);
CREATE TABLE hadid.Drivers (Id uniqueidentifier NOT NULL PRIMARY KEY, FullName nvarchar(200) NOT NULL, Phone nvarchar(50) NOT NULL, Email nvarchar(256) NULL, LicenseNumber nvarchar(80) NOT NULL UNIQUE, LicenseExpiry date NOT NULL, NationalId nvarchar(80) NULL, Status int NOT NULL, Rating decimal(3,2) NOT NULL, TotalTrips int NOT NULL, Notes nvarchar(max) NULL, AvatarUrl nvarchar(1000) NULL, CreatedAt datetimeoffset NOT NULL, UpdatedAt datetimeoffset NOT NULL, IsDeleted bit NOT NULL DEFAULT 0, DeletedAt datetimeoffset NULL);
CREATE TABLE hadid.Routes (Id uniqueidentifier NOT NULL PRIMARY KEY, Name nvarchar(200) NOT NULL, NameAr nvarchar(200) NULL, FromLocation nvarchar(300) NOT NULL, ToLocation nvarchar(300) NOT NULL, DistanceKm decimal(10,2) NULL, EstimatedDurationMinutes int NULL, BasePrice decimal(18,2) NULL, IsActive bit NOT NULL, CreatedAt datetimeoffset NOT NULL, UpdatedAt datetimeoffset NOT NULL, IsDeleted bit NOT NULL DEFAULT 0, DeletedAt datetimeoffset NULL);
CREATE TABLE hadid.Contracts (Id uniqueidentifier NOT NULL PRIMARY KEY, ContractNumber nvarchar(80) NOT NULL UNIQUE, CustomerId uniqueidentifier NULL FOREIGN KEY REFERENCES hadid.Customers(Id), CompanyId uniqueidentifier NULL FOREIGN KEY REFERENCES hadid.Companies(Id), Type int NOT NULL, Status int NOT NULL, StartDate date NULL, EndDate date NULL, MonthlyAmount decimal(18,2) NULL, TotalAmount decimal(18,2) NULL, BillingCycle int NOT NULL, Terms nvarchar(max) NULL, Notes nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL, UpdatedAt datetimeoffset NOT NULL, IsDeleted bit NOT NULL DEFAULT 0, DeletedAt datetimeoffset NULL);
CREATE TABLE hadid.Bookings (Id uniqueidentifier NOT NULL PRIMARY KEY, BookingNumber nvarchar(80) NOT NULL UNIQUE, CustomerId uniqueidentifier NULL FOREIGN KEY REFERENCES hadid.Customers(Id), ClientName nvarchar(200) NOT NULL, ClientPhone nvarchar(50) NOT NULL, ClientEmail nvarchar(256) NULL, TripType int NOT NULL, ContractType int NOT NULL, Status int NOT NULL, PickupLocation nvarchar(500) NOT NULL, Destination nvarchar(500) NOT NULL, TripDate date NOT NULL, TripTime time NOT NULL, ReturnTrip bit NOT NULL, ReturnDate date NULL, ReturnTime time NULL, Passengers int NOT NULL, VehicleId uniqueidentifier NULL FOREIGN KEY REFERENCES hadid.Vehicles(Id), DriverId uniqueidentifier NULL FOREIGN KEY REFERENCES hadid.Drivers(Id), VehiclePreference nvarchar(100) NULL, Price decimal(18,2) NULL, Source nvarchar(50) NULL, Notes nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL, UpdatedAt datetimeoffset NOT NULL, IsDeleted bit NOT NULL DEFAULT 0, DeletedAt datetimeoffset NULL);
CREATE TABLE hadid.Trips (Id uniqueidentifier NOT NULL PRIMARY KEY, BookingId uniqueidentifier NULL FOREIGN KEY REFERENCES hadid.Bookings(Id), ContractId uniqueidentifier NULL FOREIGN KEY REFERENCES hadid.Contracts(Id), VehicleId uniqueidentifier NULL FOREIGN KEY REFERENCES hadid.Vehicles(Id), DriverId uniqueidentifier NULL FOREIGN KEY REFERENCES hadid.Drivers(Id), RouteId uniqueidentifier NULL FOREIGN KEY REFERENCES hadid.Routes(Id), Status int NOT NULL, ScheduledDate date NOT NULL, ScheduledTime time NOT NULL, ActualStart datetimeoffset NULL, ActualEnd datetimeoffset NULL, PickupLocation nvarchar(500) NOT NULL, Destination nvarchar(500) NOT NULL, Passengers int NOT NULL, Notes nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL, UpdatedAt datetimeoffset NOT NULL, IsDeleted bit NOT NULL DEFAULT 0, DeletedAt datetimeoffset NULL);
CREATE TABLE hadid.Invoices (Id uniqueidentifier NOT NULL PRIMARY KEY, InvoiceNumber nvarchar(80) NOT NULL UNIQUE, CustomerId uniqueidentifier NULL FOREIGN KEY REFERENCES hadid.Customers(Id), BookingId uniqueidentifier NULL FOREIGN KEY REFERENCES hadid.Bookings(Id), ContractId uniqueidentifier NULL FOREIGN KEY REFERENCES hadid.Contracts(Id), Amount decimal(18,2) NOT NULL, TaxAmount decimal(18,2) NOT NULL, TotalAmount decimal(18,2) NOT NULL, Status int NOT NULL, DueDate date NULL, PaidDate date NULL, PaymentMethod nvarchar(80) NULL, Notes nvarchar(max) NULL, CreatedAt datetimeoffset NOT NULL, UpdatedAt datetimeoffset NOT NULL, IsDeleted bit NOT NULL DEFAULT 0, DeletedAt datetimeoffset NULL);
CREATE TABLE hadid.Payments (Id uniqueidentifier NOT NULL PRIMARY KEY, InvoiceId uniqueidentifier NOT NULL FOREIGN KEY REFERENCES hadid.Invoices(Id), Amount decimal(18,2) NOT NULL, Method nvarchar(80) NOT NULL, Reference nvarchar(160) NULL, Status int NOT NULL, PaidAt datetimeoffset NULL, CreatedAt datetimeoffset NOT NULL, UpdatedAt datetimeoffset NOT NULL, IsDeleted bit NOT NULL DEFAULT 0, DeletedAt datetimeoffset NULL);
CREATE TABLE hadid.MaintenanceRecords (Id uniqueidentifier NOT NULL PRIMARY KEY, VehicleId uniqueidentifier NOT NULL FOREIGN KEY REFERENCES hadid.Vehicles(Id), Title nvarchar(200) NOT NULL, Description nvarchar(max) NULL, ScheduledDate date NOT NULL, CompletedDate date NULL, Cost decimal(18,2) NULL, Status int NOT NULL, CreatedAt datetimeoffset NOT NULL, UpdatedAt datetimeoffset NOT NULL, IsDeleted bit NOT NULL DEFAULT 0, DeletedAt datetimeoffset NULL);
CREATE TABLE hadid.Notifications (Id uniqueidentifier NOT NULL PRIMARY KEY, UserId uniqueidentifier NULL FOREIGN KEY REFERENCES hadid.Users(Id), Title nvarchar(200) NOT NULL, Message nvarchar(1000) NOT NULL, Type nvarchar(40) NOT NULL, Status int NOT NULL, CreatedAt datetimeoffset NOT NULL, UpdatedAt datetimeoffset NOT NULL, IsDeleted bit NOT NULL DEFAULT 0, DeletedAt datetimeoffset NULL);
CREATE TABLE hadid.ActivityLogs (Id uniqueidentifier NOT NULL PRIMARY KEY, EntityType nvarchar(120) NOT NULL, EntityId uniqueidentifier NULL, Action nvarchar(120) NOT NULL, Description nvarchar(1000) NULL, UserName nvarchar(200) NULL, CreatedAt datetimeoffset NOT NULL, UpdatedAt datetimeoffset NOT NULL, IsDeleted bit NOT NULL DEFAULT 0, DeletedAt datetimeoffset NULL);
GO
CREATE INDEX IX_Bookings_TripDate_Status ON hadid.Bookings(TripDate, Status);
CREATE INDEX IX_Trips_ScheduledDate_Status ON hadid.Trips(ScheduledDate, Status);
CREATE INDEX IX_Invoices_Status ON hadid.Invoices(Status);
